UCRMS-V-1.0/Controllers/MyControllers/AssignCoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UCRMS_V_1._0.Models.MyContext;
using UCRMS_V_1._0.Models.MyModels;

namespace UCRMS_V_1._0.Controllers
{
    public class AssignCoursesController : Controller
    {
        private UcrmsDbContext db = new UcrmsDbContext();

        // GET: AssignCourses
        public async Task<ActionResult> ViewAssigningCourses()
        {
            var assignCourses = db.AssignCourses.Include(a => a.Course).Include(a => a.Department).Include(a => a.Teacher);
            return View(await assignCourses.ToListAsync());
        }



        // GET: AssignCourses/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AssignCourse assignCourse = await db.AssignCourses.FindAsync(id);
        //    if (assignCourse == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(assignCourse);
        //}

        // GET: AssignCourses/Assign
        public ActionResult Assign()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name");
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "Name");
            return View();
        }

        // POST: AssignCourses/Assign
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Assign([Bind(Include = "AssignCourseId,DepartmentId,TeacherId,CreditToBeTaken,RemainigCredit,CourseId,CourseName,CourseCredit")] AssignCourse assignCourse)
        {
            if (ModelState.IsValid)
            {
                assignCourse.Status = true;
                Teacher aTeacher = db.Teachers.FirstOrDefault(t => t.TeacherId == assignCourse.TeacherId);
                Course aCourse = db.Courses.FirstOrDefault(c => c.CourseId == assignCourse.CourseId);
                assignCourse.CreditToBeTaken = aTeacher.TakenCredit;

                List<AssignCourse> assignCourses = db.AssignCourses.Where(a => a.TeacherId == aTeacher.TeacherId).ToList();
                AssignCourse assign = null;
                if (assignCourses.Count() != 0)
                {
                    assign = assignCourses.Last();
                    assignCourse.RemainigCredit = assign.RemainigCredit;
                }
                else
                {
                    assignCourse.RemainigCredit = aTeacher.TakenCredit;
                }
                if (assignCourse.RemainigCredit < aCourse.Credit)
                {
                    if (assignCourse.RemainigCredit < aCourse.Credit)
                    {
                        Session["Teacher"] = aTeacher;
                        Session["Course"] = aCourse;
                        Session["AssignedCourse"] = assignCourse;
                        Session["AssignedCourseCheck"] = assign;
                        return RedirectToAction("AskToAssign");
                    }

                    return RedirectToAction("Assign");

                }
                assignCourse.RemainigCredit = assignCourse.RemainigCredit - aCourse.Credit;


                aCourse.AssignTo = aTeacher.TeacherId;
                db.AssignCourses.Add(assignCourse);
                db.SaveChanges();
                TempData["Successfull"] = "Course Assign Successfull";
                return RedirectToAction("Assign");
            }

            //ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", assignCourse.CourseId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", assignCourse.DepartmentId);
            //ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "Name", assignCourse.TeacherId);
            return View(assignCourse);
        }
        //GET: UnAssignCourse
        public ActionResult UnAssignCourse()
        {
            // var list = from p in db.AssignCourses where p.Status.Equals(true) select p;
            var list = from p in db.Courses where p.Status.Equals(true) select p;

            foreach (var course in list)
            {
                course.Status = false;
                //db.AssignCourses.Remove(course);
            }

            //var list2 = from p2 in db.Courses where p2.AssignTo != null select p2;
            //foreach (var assign in list2)
            //{

            //}

            db.SaveChanges();
            return View();
        }

        //GET: ViewCourseStatics
        public ActionResult ViewCourseStatics(int? id)
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            var courses = db.Courses.Where(c => c.CourseId == id);

            //var assigncourses = db.AssignCourses.Include(a => a.Course).Include(a => a.Department).Include(a => a.Teacher).Where(t=>t.DepartmentId==departmentId);

            return View(courses);
        }
        //GET: LoadCourseStatics
        //public PartialViewResult LoadCourseStatics( int? departmentId )
        //{

        //       var courseList = db.Courses.Join(db.Teachers,x=>x.AssignTo,y=>y.TeacherId,(x,y)=>new
        //        {
        //            Course=x,Teacher=y
        //        })
        //        .Select(x=> new
        //        {
        //            x.Course.Code,
        //            x.Course.Name,
        //            x.Course.Semester,
        //            Teacher=x.Teacher.Name
        //        }).ToList();
        //    return PartialView("LoadCourseStatics", courseList);
        //}

        [HttpGet]
        public JsonResult GetCourseStatics(int? departmentId)
        {
            var courseList = db.Courses.GroupJoin(db.Teachers, x => x.AssignTo, y => y.TeacherId, (x, y)
                => new { Course = x, Teacher1 = y.DefaultIfEmpty().Select(a => string.IsNullOrEmpty(a.Name) ? "Not Assigned Yet" : a.Name).FirstOrDefault() })
                .Where(x => x.Course.DepartmentId == departmentId)
                //.Where( x => (x.Course.DepartmentId == departmentId) && (x.Course.Status==false))
             .Select(x => new
             {
                 x.Course.Code,
                 x.Course.Name,
                 Semester = x.Course.Semester.Name,
                 Teacher = x.Teacher1
             }).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        //Get: LoadTeachers
        public ActionResult LoadTeacher(int? departmentId)
        {

            var teachers = db.Teachers.Where(m => m.DepartmentId == departmentId).ToList();
            ViewBag.TeacherId = new SelectList(teachers, "TeacherId", "Name");

            return PartialView("LoadTeacher");
        }
        //Get: LoadTeacherInfo
        public PartialViewResult LoadTeacherInfo(int? teacherId)
        {
            if (teacherId != null)
            {
                Teacher aTeacher = db.Teachers.FirstOrDefault(t => t.TeacherId == teacherId);

                ViewBag.TakenCredit = aTeacher.TakenCredit;
                List<AssignCourse> assignCourses = db.AssignCourses.Where(m => m.TeacherId == teacherId).ToList();

                AssignCourse assign = null;

                if (assignCourses.Count != 0)
                {
                    assign = assignCourses.Last();
                }

                if (assign == null)
                {
                    ViewBag.RemaingCredit = aTeacher.TakenCredit;
                }
                else
                {
                    ViewBag.RemaingCredit = assign.RemainigCredit;
                }
                return PartialView("LoadTeacherInfo");
            }
            return PartialView("LoadTeacherInfo");
        }
        //Get: LoadCourses
        public ActionResult LoadCourse(int? departmentId)
        {

            var courseList = db.Courses.Where(m => m.DepartmentId == departmentId).ToList();
            var assignCourse = db.AssignCourses.Where(m => m.DepartmentId == departmentId).ToList();


            foreach (var assign in assignCourse)
            {
                courseList.Remove(db.Courses.FirstOrDefault(t => t.CourseId == assign.CourseId));
            }


            ViewBag.CourseId = new SelectList(courseList, "CourseId", "Code");

            return PartialView("LoadCourse");
        }
        //Get: LoadCourseInfo
        public PartialViewResult LoadCourseinfo(int? courseId)
        {
            if (courseId != null)
            {
                Course aCourse = db.Courses.FirstOrDefault(t => t.CourseId == courseId);

                ViewBag.Name = aCourse.Name;
                ViewBag.Credit = aCourse.Credit;
                return PartialView("LoadCourseinfo");
            }
            return PartialView("LoadCourseinfo");
        }




        //// GET: AssignCourses/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AssignCourse assignCourse = await db.AssignCourses.FindAsync(id);
        //    if (assignCourse == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", assignCourse.CourseId);
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", assignCourse.DepartmentId);

UCRMS-V-1.0/Views/AssignCourses/AskToAssign.cshtml
@model dynamic

@{
    ViewBag.Title = "AskToAssign";

}

<h2>Assign confirmation </h2>
<div>

    <h3 style="color: firebrick">@ViewBag.Message</h3>
</div>
<form action="AssignConfirmed">
   <input type="submit" value="Yes" class="btn btn-success"/>

</form>
<p><br /></p>
<form action="Assign">
    <input type="submit" value="No" class="btn btn-warning" />
</form>

UCRMS-V-1.0/Views/AssignCourses/Assign.cshtml
@model UCRMS_V_1._0.Models.MyModels.AssignCourse

@{
    ViewBag.Title = "Course Assign To Teacher";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (TempData["Successfull"] != null)
    {
        <label style="color: green">@TempData["Successfull"]</label>
    }
    <div class="form-horizontal">
        <h2>Course Assign to Teacher</h2>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Partial("LoadTeacher", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div id="TeacherInfo">
            @Html.Partial("LoadTeacherInfo")
        </div>
       <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Course Code", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Partial("LoadCourse")
                @Html.ValidationMessageFor(model => model.CourseId,"", new { @class = "text-danger" })
            </div>
        </div>

        <div id="CourseInfo">
            @Html.Partial("LoadCourseinfo")
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Assign" id="buttonClick" class="btn btn-success"/>
            </div>
        </div>
       
    </div>
}
@if (ViewBag.sh != null)
{
    <script>
        $("#buttonClick").submitted(function () {
            var result = confirm("Are you sure you want to assign Course To this Teacher ?");
            if (result) {
                document.location = '@Url.Action("Assign","AssignCourses")';
            }
            else {
                alert("Course are not Assigned");
            }

            return false;
        });
    </script>
}
<div>
    @Html.ActionLink("View All Assigning Courses", "ViewAssigningCourses")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/modalscript.js"></script>

<script>


    function FillData(id) {
        $("#TeacherId").load('@Url.Action("LoadTeacher")', { departmentId: id });
        $("#CourseId").load('@Url.Action("LoadCourse")', { departmentId: id });
    }

    function FillTeacherInfo(id) {
        $("#TeacherInfo").load('@Url.Action("LoadTeacherInfo")', { teacherId: id });
    }
    function FillCourseInfo(id) {
        $("#CourseInfo").load('@Url.Action("LoadCourseinfo")', { courseId: id });
    }


    $(document).ready($(function () {
        $("#DepartmentId").change(function () {
            var id = $("#DepartmentId").val();
            FillData(id);

        });
        $("#TeacherId").change(function () {
            var id = $("#TeacherId").val();
            FillTeacherInfo(id);

        });

        $("#CourseId").change(function () {
            var id = $("#CourseId").val();
            FillCourseInfo(id);

        });


    }));
</script>

UCRMS-V-1.0/Views/AssignCourses/AssignConfirmed.cshtml
@model dynamic

@{
    ViewBag.Title = "AssignConfirmed";
}

<div>

    <h3 style="color: green">@TempData["success"]</h3>
</div>
<br/>
<form action="Assign">
    <input type="submit" value="Assign New Course" class="btn btn-success" />
</form>

UCRMS-V-1.0/Views/AssignCourses/Delete.cshtml
@model UCRMS_V_1._0.Models.MyModels.AssignCourse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AssignCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditToBeTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditToBeTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainigCredit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainigCredit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewAssigningCourses")
        </div>
    }
</div>

UCRMS-V-1.0/Views/AssignCourses/Details.cshtml
@model UCRMS_V_1._0.Models.MyModels.AssignCourse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AssignCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditToBeTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditToBeTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainigCredit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainigCredit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AssignCourseId }) |
    @Html.ActionLink("Back to List", "ViewAssigningCourses")
</p>

UCRMS-V-1.0/Views/AssignCourses/Edit.cshtml
@model UCRMS_V_1._0.Models.MyModels.AssignCourse

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AssignCourse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AssignCourseId)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditToBeTaken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditToBeTaken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditToBeTaken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RemainigCredit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RemainigCredit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RemainigCredit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewAssigningCourses")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCRMS-V-1.0/Views/AssignCourses/LoadCourse.cshtml
@model dynamic

@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", String.Empty)
}

UCRMS-V-1.0/Views/AssignCourses/LoadCourseStatics.cshtml
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.Course>

@if (Model != null)
{
    <table class="table table-striped">
        <tr>
            <th>
                Code
            </th>
            <th>
                Name/Title
            </th>
            <th>
                Semester
            </th>
            <th>
                Assigned To
            </th>
        </tr>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Semester.Name)
                </td>
                <td>
                    @if (item.AssignTo != null)
                    {
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    }
                    @if (item.AssignTo == null)
                    {
                        item.AssignTo = "Not Assigned Yet";
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    }
                </td>
            </tr>
        }
    </table>
}

UCRMS-V-1.0/Views/AssignCourses/LoadCourseinfo.cshtml
@model dynamic

<div id="CourseInfo">
    <div class="form-group">
        @Html.Label("Course Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Name
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Credit", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Credit

        </div>
    </div>
</div>

UCRMS-V-1.0/Views/AssignCourses/LoadTeacher.cshtml
@if (ViewBag.TeacherId != null)
{
    @Html.DropDownList("TeacherId", String.Empty)
}

UCRMS-V-1.0/Views/AssignCourses/LoadTeacherInfo.cshtml
@model dynamic

<div id="TeacherInfo">
    <div class="form-group">
        @*@Html.LabelFor(model => model.CreditToBeTaken, new { @class = "control-label col-md-2" })*@
        @Html.Label("Credit To Be Taken", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.TakenCredit
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Remaing Credit", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.RemaingCredit
        </div>
    </div>
</div>

UCRMS-V-1.0/Views/AssignCourses/UnAssignCourse.cshtml
@{
    ViewBag.Title = "UnAssignCourse";
}

<fieldset>
    <legend>Unassign All Courses</legend>

    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        if (ViewBag.Success != null)
        {
            @ViewBag.Success
        }

        <div class="form-horizontal">
            @Html.ValidationSummary(true)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Unassign Courses" class="btn btn-danger" id="buttonClick" />
                </div>
            </div>
        </div>
    }

</fieldset>

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    $("#buttonClick").click(function () {
        var result = confirm("Are you sure you want to unassign all the courses ?");
        if (result) {
            document.location = '@Url.Action("UnAssignCourse","AssignCourses")';
        }
        else {
            alert("Courses are not unassigned");
        }

        return false;
    });
</script>

UCRMS-V-1.0/Views/AssignCourses/ViewAssigningCourses.cshtml
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.AssignCourse>

@{
    ViewBag.Title = "ViewAssigningCourses";
}

<h2>All Assigning Course's List</h2>

<p>
    @Html.ActionLink("Assign New", "Assign")
</p>
<table class="table">
    <tr>
        <th>
            Teacher
        </th>
        <th>
            Department
        </th>

        <th>
            Course
        </th>

        <th>
            Creadit to be Taken
        </th>
        <th>
            @*@Html.DisplayNameFor(model=>model.RemainigCredit)*@
            Remaining Credit
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Course.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.CreditToBeTaken)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RemainigCredit)
            </td>

            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.AssignCourseId }) |
                    @Html.ActionLink("Details", "Details", new { id=item.AssignCourseId }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.AssignCourseId })
                </td>*@
        </tr>
    }

</table>

UCRMS-V-1.0/Views/AssignCourses/ViewCourseStatics.cshtml
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.Course>

@{
    ViewBag.Title = "View Course Statics";
}

<h2>View Course Statics</h2>




@using (Html.BeginForm())
{
    <div>
        <b>Select Department  </b>
        @Html.DropDownList("DepartmentId", string.Empty)
    </div>
}
<p><br /></p>

<h2>Course Information</h2>
<p><br /></p>


<div id="CourseStatics">
    <table class="table table-striped">
        <tr>
            <th>
                Code
            </th>
            <th>
                Name/Title
            </th>
            <th>
                Semester
            </th>
            <th>
                Assigned To
            </th>
        </tr>
        <tbody id="tblAssignCourse"></tbody>
    </table>

</div>
<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>

$(document).ready(function ()
{
    $("#DepartmentId").change(function () {
        var id = $("#DepartmentId").val();
        $.ajax({
            type: "GET",
            url: "@(Url.Action("GetCourseStatics", "AssignCourses"))",
            data: { departmentId: id },
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                var row = "";
                $.each(data, function (index, item) {
                    row += "<tr>" +
                        "<td>" + item.Code + "</td>"+
                        "<td>" + item.Name + "</td>" +
                        "<td>" + item.Semester + "</td>" +
                        "<td>" + item.Teacher + "</td>" +
                        "</tr>";
                });
                $("#tblAssignCourse").html(row);
            },
            error: function () {
            }

        });

    });

    });
</script>