UCRMS-V-1.0/Models/MyModels/AllocateClassRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UCRMS_V_1._0.Models.MyModels
{
    public class AllocateClassRoom
    {
        public int AllocateClassRoomId { get; set; }

        [Required(ErrorMessage = "Please Select A Department")]
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "Please Select A Course")]
        public int CourseId { get; set; }

        [Required(ErrorMessage = "Please Select A Room")]
        public int RoomId { get; set; }
        [Required(ErrorMessage = "Please Select A Day")]
        public int DayId { get; set; }

        [Required(ErrorMessage = "Please Set The Class Time")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = @"{0:hh\:mm}")]
        public DateTime From { get; set; }

        [Required(ErrorMessage = "Please Set The Class Time")]
        [DataType(DataType.Time)]

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = @"{0:hh\:mm}")]
        public DateTime To { get; set; }

        public virtual Department Department { get; set; }
        public virtual Course Course { get; set; }
        public virtual Room Room { get; set; }
        public virtual Day Day { get; set; }
        public bool Status { get; set; }
    }
}

UCRMS-V-1.0/Controllers/MyControllers/AllocateClassRoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using UCRMS_V_1._0.Models.MyContext;
using UCRMS_V_1._0.Models.MyModels;

namespace UCRMS_V_1._0.Controllers.MyControllers
{
    public class AllocateClassRoomsController : Controller
    {
        private UcrmsDbContext db = new UcrmsDbContext();

        // GET: AllocateClassRooms
        public async Task<ActionResult> ViewAllocations()
        {
            var allocateClassRooms = db.AllocateClassRooms.Include(a => a.Course).Include(a => a.Day).Include(a => a.Department).Include(a => a.Room);
            return View(await allocateClassRooms.ToListAsync());
        }

        // GET: AllocateClassRooms/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AllocateClassRoom allocateClassRoom = await db.AllocateClassRooms.FindAsync(id);
        //    if (allocateClassRoom == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(allocateClassRoom);
        //}

        // GET: AllocateClassRooms/Allocate
        public ActionResult Allocate()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name");
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name");
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name");
            return View();
        }

        // POST: AllocateClassRooms/Allocate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Allocate( [Bind(Include = "AllocateClassRoomId,DepartmentId,CourseId,RoomId,DayId,From,To")] AllocateClassRoom allocateClassRoom )
        {
            if (ModelState.IsValid)
            {
                List<AllocateClassRoom> allocateClassRooms =
                    db.AllocateClassRooms.Where(
                        t =>
                            (t.RoomId == allocateClassRoom.RoomId) && (t.DayId == allocateClassRoom.DayId) &&
                            ((t.From <= allocateClassRoom.From && t.To >= allocateClassRoom.From) ||
                            (t.From <= allocateClassRoom.To && t.To >= allocateClassRoom.To) ||
                            (t.From >= allocateClassRoom.From && t.From <= allocateClassRoom.To) ||
                            (t.To >= allocateClassRoom.From && t.To <= allocateClassRoom.To)
                            )).ToList();

                if (allocateClassRooms.Count == 0)
                {
                    db.AllocateClassRooms.Add(allocateClassRoom);
                    db.SaveChanges();
                    TempData["Msg"] = "Class Allocate Successfull";
                }
                else
                {
                    TempData["Msgf"] = "Can't Allocate Class in Same Room During other class";
                }

                return RedirectToAction("Allocate");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", allocateClassRoom.CourseId);
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", allocateClassRoom.DayId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", allocateClassRoom.DepartmentId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", allocateClassRoom.RoomId);
            return View(allocateClassRoom);
        }
        //GET: AllocateClassRooms/LoadCourse
        public ActionResult LoadCourse( int? departmentId )
        {

            var courseList = db.Courses.Where(m => m.DepartmentId == departmentId).ToList();
            //var assignCourse = db.AssignCourses.Where(m => m.DepartmentId == departmentId).ToList();


            ViewBag.CourseId = new SelectList(courseList, "CourseId", "Name");


            return PartialView("LoadCourse");
        }

        // GET: AllocateClassRooms/UnAllocate
        public ActionResult UnallocateClassRoom()
        {
            var rooms = from p in db.AllocateClassRooms where p.Status.Equals(false) select p;

            foreach (var roomAllocation in rooms)
            {
                db.AllocateClassRooms.Remove(roomAllocation);
            }
            db.SaveChanges();
            return View();
        }

        // GET: /AllocateClassRoom/ViewStudents
        public ActionResult ViewSchedule()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            return View();
        }
        
        public JsonResult GetCourseByDept( int? departmentId )
        {
            var courseList = db.Courses
                .Where(x => x.DepartmentId == departmentId)
                .Select(x => new
                {
                    x.CourseId,
                    x.Code,
                    x.Name,

                }).ToList();

            return Json(courseList, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult GetScheduleInfo( int? courseId )
        {

            var courseList = db.AllocateClassRooms
                        .Where(x => x.CourseId == courseId)
                        .Select(x => new
                        {
                            x.From,
                            x.To,
                            x.Room.Name,
                            DayName=x.Day.Name,
                          //  Semester = x.Course.Semester.Name,
                            Schedule = "R. No :" + x.Room.Name + ", " +
                            x.Day.Name + " " + x.From + " - " + x.To
                        }).ToList();

            return Json(courseList, JsonRequestBehavior.AllowGet);

        }



        //// GET: AllocateClassRooms/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AllocateClassRoom allocateClassRoom = await db.AllocateClassRooms.FindAsync(id);
        //    if (allocateClassRoom == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", allocateClassRoom.CourseId);
        //    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", allocateClassRoom.DayId);
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", allocateClassRoom.DepartmentId);
        //    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", allocateClassRoom.RoomId);
        //    return View(allocateClassRoom);
        //}

        //// POST: AllocateClassRooms/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "AllocateClassRoomId,DepartmentId,CourseId,RoomId,DayId,From,To,Status")] AllocateClassRoom allocateClassRoom)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(allocateClassRoom).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("ViewStudents");
        //    }
        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", allocateClassRoom.CourseId);
        //    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", allocateClassRoom.DayId);
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", allocateClassRoom.DepartmentId);
        //    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", allocateClassRoom.RoomId);
        //    return View(allocateClassRoom);
        //}

        //// GET: AllocateClassRooms/Delete/5
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AllocateClassRoom allocateClassRoom = await db.AllocateClassRooms.FindAsync(id);
        //    if (allocateClassRoom == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(allocateClassRoom);
        //}

        //// POST: AllocateClassRooms/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    AllocateClassRoom allocateClassRoom = await db.AllocateClassRooms.FindAsync(id);
        //    db.AllocateClassRooms.Remove(allocateClassRoom);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("ViewStudents");
        //}

        protected override void Dispose( bool disposing )
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UCRMS-V-1.0/Views/AllocateClassRooms/Allocate.cshtml
@model UCRMS_V_1._0.Models.MyModels.AllocateClassRoom

@{
    ViewBag.Title = "Allocate Class Room";
}

<h2>Allocate Class Room</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (TempData["Msg"] != null)
    {
        <label style="color: green">@TempData["Msg"]</label>
    }
    else
    {
        <label style="color: red">@TempData["Msgf"]</label>
    }

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "Room No", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayId, "Day", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                        <td>@Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })</td>
                    </tr>
                </table>
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                        <td>@Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })</td>
                    </tr>
                </table>
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.From, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.From, new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.From)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.To, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.To, new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.To)
                </div>
            </div>*@



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Allocate" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View Allocation's List", "ViewAllocations")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    function FillData(id) {
        $("#CourseId").load('@Url.Action("LoadCourse")', { departmentId: id });
    }
    $(document).ready($(function () {
        $("#DepartmentId").change(function () {
            var id = $("#DepartmentId").val();
            FillData(id);

        });
    }));
</script>

UCRMS-V-1.0/Views/AllocateClassRooms/Delete.cshtml
@model UCRMS_V_1._0.Models.MyModels.AllocateClassRoom

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AllocateClassRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewAllocations")
        </div>
    }
</div>

UCRMS-V-1.0/Views/AllocateClassRooms/Details.cshtml
@model UCRMS_V_1._0.Models.MyModels.AllocateClassRoom

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AllocateClassRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AllocateClassRoomId }) |
    @Html.ActionLink("Back to List", "ViewAllocations")
</p>

UCRMS-V-1.0/Views/AllocateClassRooms/Edit.cshtml
@model UCRMS_V_1._0.Models.MyModels.AllocateClassRoom

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AllocateClassRoom</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AllocateClassRoomId)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayId, "DayId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewAllocations")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCRMS-V-1.0/Views/AllocateClassRooms/LoadCourse.cshtml
@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", String.Empty)
}

UCRMS-V-1.0/Views/AllocateClassRooms/UnallocateClassRoom.cshtml
@{
    ViewBag.Title = "UnallocateClassRoom";
}


<fieldset>
    <legend>Unallocate Rooms</legend>

    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        if (ViewBag.Success != null)
        {
            @ViewBag.Success
        }

        <div class="form-horizontal">
            @Html.ValidationSummary(true)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Unallocate Rooms" class="btn btn-danger" id="buttonPressed" />
                </div>
            </div>
        </div>
    }

</fieldset>

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    $("#buttonPressed").click(function () {
        var result = confirm("Are you sure you want to unassign all the ClassRoom ?");
        if (result) {
            document.location = '@Url.Action("UnallocateClassRoom", "AllocateClassRooms")';
        }
        else {
            alert("Class are not unassigned");
        }

        return false;
    });
</script>

UCRMS-V-1.0/Views/AllocateClassRooms/ViewAllocations.cshtml
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.AllocateClassRoom>

@{
    ViewBag.Title = "ViewAllocations";
}

<h2>View Allocations</h2>

<p>
    @Html.ActionLink("Allocate New", "Allocate")
</p>
<table class="table">
    <tr>
        <th>
            Course-Code
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.Name)
        </th>
        
        <th>
            Department
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Room.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Day.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.To)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Department.Name)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Room.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Day.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.To)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AllocateClassRoomId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AllocateClassRoomId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AllocateClassRoomId })
        </td>*@
    </tr>
}

</table>

UCRMS-V-1.0/Views/AllocateClassRooms/ViewSchedule.cshtml
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.Course>

@{
    ViewBag.Title = "ViewSchedule";
}

<h2>View Class Schedule & Room Allocation Information</h2>

@using (Html.BeginForm())
{
    <div>
        <b>Select Department  </b>
        @Html.DropDownList("DepartmentId", string.Empty)
    </div>
}
<br /><p>
    @Html.ActionLink("Allocate New", "Allocate")
</p>
<p><br /></p>


<p><br /></p>

<div id="ClassScheduleInfo">
    <table class="table table-striped">
        <tr>
            <th>
                Code
            </th>
            <th>
                Name
            </th>
            <th>
                Schedule Info
            </th>
        </tr>
        <tbody id="tblViewSchedule"></tbody>
    </table>
</div>
<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>



    $(document).ready(function () {

        function SendAjax(jsData, url, type, successMessage, str) {
            var returnData = "";
            $.ajax({
                async: false,
                type: type,
                url: url,
                data: str === "" ? JSON.stringify(jsData) : jsData, //JSON.stringify(jsData),
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    //alert(row);
                    returnData = data;
                },
                error: function () {
                }

            });
            return returnData;
        }

        $("#DepartmentId").change(function () {
            var id = $("#DepartmentId").val();
            $.ajax({
                type: "GET",
                url: "@(Url.Action("GetCourseByDept", "AllocateClassRooms"))",
                data: { departmentId: id },
                contentType: "application/json;charset=utf-8",
                success: function (data) {

                    var row = "";
                    $.each(data, function (index, item) {
                        var assignUrl="@(Url.Action("GetScheduleInfo", "AllocateClassRooms"))";
                        var scheduleList = SendAjax({ courseId: item.CourseId }, assignUrl, "POST", "", "");
                        var scheduleTable = "";
                        $.each(scheduleList, function (index1, scheduleitem) {
                            //alert(scheduleitem.Schedule);
                            scheduleTable += "<p>" + scheduleitem.Schedule+"</p>";
                        });

                        row += "<tr>" +
                            "<td>" + item.Code + "</td>"+
                            "<td>" + item.Name + "</td>" +
                            "<td>" + scheduleTable + "</td>" +
                            "</tr>";
                    });
                    $("#tblViewSchedule").html(row);
                },
                error: function () {
                }

            });

        });

    });
</script>