UCRMS-V-1.0/Models/MyModels/SaveResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UCRMS_V_1._0.Models.MyModels
{
    public class SaveResult
    {
        public int SaveResultId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public int GradeId { get; set; }

        public virtual Student Student { get; set; }
        public virtual Course Course { get; set; }
        public virtual Grade Grade { get; set; }
    }
}

UCRMS-V-1.0/Models/MyModels/ViewResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UCRMS_V_1._0.Models.MyModels
{
    public class ViewResult
    {
        public int ViewResultId { get; set; }
        public string CourseCode { set; get; }
        public string CourseName { set; get; }
        public string Grade { set; get; }
    }
}

UCRMS-V-1.0/Controllers/MyControllers/SaveResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UCRMS_V_1._0.Models.MyContext;
using UCRMS_V_1._0.Models.MyModels;

namespace UCRMS_V_1._0.Controllers.MyControllers
{
    public class SaveResultsController : Controller
    {
        private UcrmsDbContext db = new UcrmsDbContext();

        // GET: SaveResults/ViewResult
        public ActionResult ViewResult( int? id )
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");

            //            var studentresults = db.SaveResults.Where(s=>s.StudentId==id);
            var courseList = db.Courses.Where(s => s.CourseId == id);
            return View(courseList);
        }

        //// GET: SaveResults/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    SaveResult saveResult = await db.SaveResults.FindAsync(id);
        //    if (saveResult == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(saveResult);
        //}

        // GET: SaveResults/SaveResult
        public ActionResult SaveResult()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name");
            ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "Name");
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");
            return View();
        }

        // POST: SaveResults/SaveResult
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveResult( [Bind(Include = "SaveResultId,StudentId,CourseId,GradeId")] SaveResult saveResult )
        {
            if (ModelState.IsValid)
            {
                db.SaveResults.Add(saveResult);
                await db.SaveChangesAsync();
                TempData["Msg"] = "Successfully Saved Student Result";
                return RedirectToAction("SaveResult");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", saveResult.CourseId);
            ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "Name", saveResult.GradeId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo", saveResult.StudentId);
            return View(saveResult);
        }

        //GET: SaveResults/LoadStudentInfo
        public PartialViewResult LoadStudentInfo( int? studentId )
        {
            if (studentId != null)
            {
                Student aStudent = db.Students.FirstOrDefault(s => s.StudentId == studentId);

                ViewBag.Name = aStudent.Name;
                ViewBag.Email = aStudent.Email;
                ViewBag.Department = aStudent.Department.Name;
                return PartialView("LoadStudentInfo");
            }
            return PartialView("LoadStudentInfo");
        }

        //GET: SaveResults/LoadCourses
        public ActionResult LoadCourse( int? studentId )
        {

            Student aStudent = db.Students.FirstOrDefault(s => s.StudentId == studentId);

            var enrollCourses = db.EnrollCourses.Where(t => t.StudentId == studentId).ToList();

            List<Course> courseList = new List<Course>();
            foreach (var enrollCourse in enrollCourses)
            {
                courseList.Add(db.Courses.FirstOrDefault(t => t.CourseId == enrollCourse.CourseId));
            }


            ViewBag.CourseId = new SelectList(courseList, "CourseId", "Name");

            return PartialView("LoadCourse");
        }

        //GET: SaveResults/LoadResult
        public PartialViewResult LoadResult( int studentId )
        {
            var students = db.Students.Where(s => s.StudentId == studentId);
            var enrollCourses = db.EnrollCourses.Where(t => t.StudentId == studentId).ToList();
            var studentResults = db.SaveResults.Where(s => s.StudentId == studentId).ToList();
            List<Course> courseList = new List<Course>();
            foreach (var enrollCourse in enrollCourses)
            {
                courseList.Add(db.Courses.FirstOrDefault(t => t.CourseId == enrollCourse.CourseId));
            }
            foreach (var course in courseList)
            {
                foreach (var studentResult in studentResults)
                {
                    if (course.CourseId == studentResult.CourseId)
                    {
                        course.Grade = studentResult.Grade.Name;
                    }
                }
            }

            return PartialView("LoadResult", courseList);
        }

        //GET: SaveResult/GeneratePDF
        public ActionResult GeneratePdf( int? studentId )
        {
            return new Rotativa.ActionAsPdf("MakePdf", new { studentId = studentId });
        }

        //GET: SaveResult/MakePDF
        public ActionResult MakePdf( int? studentId )
        {
            Student aStudent = new Student();
            Student desiredStudent = db.Students.FirstOrDefault(t => t.StudentId == studentId);
            if (desiredStudent != null)
            {
                aStudent.Name = desiredStudent.Name;
                aStudent.Email = desiredStudent.Email;
                aStudent.RegNo = desiredStudent.RegNo;
                aStudent.Department = desiredStudent.Department;

            }

            aStudent.ResultDate = DateTime.Now;

            var enrollCourses = db.EnrollCourses.Where(t => t.StudentId == studentId).ToList();
            var studentResults = db.SaveResults.Where(s => s.StudentId == studentId).ToList();
            List<Course> courseList = new List<Course>();
            foreach (var enrollCourse in enrollCourses)
            {
                courseList.Add(db.Courses.FirstOrDefault(t => t.CourseId == enrollCourse.CourseId));
            }
            foreach (var course in courseList)
            {
                foreach (var studentResult in studentResults)
                {
                    if (course.CourseId == studentResult.CourseId)
                    {
                        course.Grade = studentResult.Grade.Name;
                    }
                }
            }
            aStudent.Courses = courseList;


            return View(aStudent);
        }

        //// GET: SaveResults/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    SaveResult saveResult = await db.SaveResults.FindAsync(id);
        //    if (saveResult == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", saveResult.CourseId);
        //    ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "Name", saveResult.GradeId);
        //    ViewBag.StudentId = new SelectList(db.Students, "StudentId", "Name", saveResult.StudentId);
        //    return View(saveResult);
        //}

        //// POST: SaveResults/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "SaveResultId,StudentId,CourseId,GradeId")] SaveResult saveResult)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(saveResult).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("ViewResult");
        //    }
        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", saveResult.CourseId);
        //    ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "Name", saveResult.GradeId);
        //    ViewBag.StudentId = new SelectList(db.Students, "StudentId", "Name", saveResult.StudentId);
        //    return View(saveResult);
        //}

        //// GET: SaveResults/Delete/5
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    SaveResult saveResult = await db.SaveResults.FindAsync(id);
        //    if (saveResult == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(saveResult);
        //}

        //// POST: SaveResults/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    SaveResult saveResult = await db.SaveResults.FindAsync(id);
        //    db.SaveResults.Remove(saveResult);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("ViewResult");
        //}

        protected override void Dispose( bool disposing )
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

UCRMS-V-1.0/Views/SaveResults/Delete.cshtml
@model UCRMS_V_1._0.Models.MyModels.SaveResult

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SaveResult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewResult")
        </div>
    }
</div>

UCRMS-V-1.0/Views/SaveResults/Details.cshtml
@model UCRMS_V_1._0.Models.MyModels.SaveResult

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SaveResult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SaveResultId }) |
    @Html.ActionLink("Back to List", "ViewResult")
</p>*@

UCRMS-V-1.0/Views/SaveResults/Edit.cshtml
@model UCRMS_V_1._0.Models.MyModels.SaveResult

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SaveResult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SaveResultId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradeId, "GradeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GradeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewResult")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCRMS-V-1.0/Views/SaveResults/LoadCourse.cshtml
@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", String.Empty)
}

UCRMS-V-1.0/Views/SaveResults/LoadResult.cshtml
@model  IEnumerable<UCRMS_V_1._0.Models.MyModels.Course>

<table class="table">
    <tr>
        <th>
           Course Code
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (item.Grade != null)
                {
                    @Html.DisplayFor(modelItem => item.Grade)
                }
                else
                {
                    <p>Not Graded Yet</p>
                }

            </td>
        </tr>
    }

</table>

UCRMS-V-1.0/Views/SaveResults/LoadStudentInfo.cshtml
<div id="StudentInfo">
    <div class="form-group">
        @Html.Label("Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Name
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Email", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Email

        </div>
    </div>

    <div class="form-group">
        @Html.Label("Department", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Department

        </div>
    </div>
</div>

UCRMS-V-1.0/Views/SaveResults/MakePdf.cshtml
@model UCRMS_V_1._0.Models.MyModels.Student

@{
    ViewBag.Title = "ViewResult";
    Layout = "";
}

<h2 style="color: blue">University Of Engineering And Technology</h2>

<fieldset style="border: 1px solid green; padding: 15px">


    <legend style="color: green">Student Result Information</legend>
    <br />
    <br />
    <br />


    <div id="StudentInfo">
        <div class="form-group">
            <b>Registration Number : </b>

            @Html.DisplayFor(model => model.RegNo)


        </div>



        <div class="form-group">
            <b>Name        : </b>
            @Html.DisplayFor(model => model.Name)


        </div>

        <div class="form-group">
            <b>Email      :</b>
            @Html.DisplayFor(model => model.Email)

        </div>

        <div class="form-group">
            <b>Departmet    :</b>
            @Html.DisplayFor(model => model.Department.Name)


        </div>
    </div>

    <div id="LoadResultInfo">
        <table class="table" style="border: 1px solid skyblue; height: 400px; width: 960px">
            <tr>
                <th>
                    Course Code
                </th>
                <th>
                    Course Name

                </th>
                <th>
                    Grade
                </th>
                <th></th>
            </tr>

            <tr></tr>
            @foreach (var item in Model.Courses)
            {
                <tr>
                    <td style="border: 1px solid skyblue">
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td style="border: 1px solid skyblue">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="border: 1px solid skyblue">
                        @if (item.Grade != null)
                        {
                            @Html.DisplayFor(modelItem => item.Grade)
                        }
                        else
                        {
                            <p>Not Graded Yet</p>
                        }

                    </td>
                </tr>
            }

        </table>
    </div>

    <b style="color: red">Print Date  :  @Model.ResultDate </b>
</fieldset>

UCRMS-V-1.0/Views/SaveResults/SaveResult.cshtml
@model UCRMS_V_1._0.Models.MyModels.SaveResult

@{
    ViewBag.Title = "SaveResult";
}

<h2>Save Student Result</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (TempData["Msg"] != null)
    {
        <h3 style="color: green">@TempData["Msg"]</h3>
    }

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Student Reg. No.", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.StudentId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div id="StudentInfo">
            @Html.Partial("LoadStudentInfo")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Select Course", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.Partial("LoadCourse")
            </div>
        </div>



        @*<div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Select Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.GradeId, "Select Grate Letter", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GradeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SaveResult" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View All Results", "ViewResult")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    function FillStudentInfo(id) {
        $("#StudentInfo").load('@Url.Action("LoadStudentInfo")', { studentId: id });
    }
    function FillCourse(id) {
        $("#CourseId").load('@Url.Action("LoadCourse")', { studentId: id });
    }

    $(document).ready($(function() {
        $("#StudentId").change(function() {
            var id = $("#StudentId").val();
            FillStudentInfo(id);
            FillCourse(id);

        });
    }));
</script>

UCRMS-V-1.0/Views/SaveResults/ViewResult.cshtml
@using System.Collections
@using UCRMS_V_1._0.Models.MyModels
@model IEnumerable<UCRMS_V_1._0.Models.MyModels.Course>

@{
    ViewBag.Title = "ViewResult";
}

<h2>View Result</h2>

<p>
    @Html.ActionLink("Save New Result", "SaveResult")
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        
        <div class="form-group">
            <div class="col-md-10">
                <b>Student Reg. No.</b>
                @Html.DropDownList("StudentId", String.Empty)
            </div>
        </div>

        <div id="StudentInfo">
            @Html.Partial("LoadStudentInfo")
        </div>
    </div>

    <input type="button" value="Make PDF" id="MakePdf" class="btn btn-info" />

}
<div id="LoadResultInfo">
    @Html.Partial("LoadResult")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    function FillStudentInfo(id) {
        $("#StudentInfo").load('@Url.Action("LoadStudentInfo")', { studentId: id });
    }
    function FillData(id) {
        $('#LoadResultInfo').load('@Url.Action("LoadResult")', { studentId: id });
    }

    $(document).ready($(function () {
        $("#StudentId").change(function () {
            var id = $("#StudentId").val();
            FillStudentInfo(id);
            FillData(id);

        });
        $("#MakePdf").click(function () {
            var studentId = $("#StudentId").val();
            document.location = '@Url.Action("GeneratePDF", "SaveResults")' + '?' + 'studentId=' + studentId;

            return false;
        });
    }));
</script>