UCRMS-V-1.0/Controllers/MyControllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UCRMS_V_1._0.Models.MyContext;
using UCRMS_V_1._0.Models.MyModels;

namespace UCRMS_V_1._0.Controllers.MyControllers
{
    public class CoursesController : Controller
    {
        private UcrmsDbContext db = new UcrmsDbContext();

        // GET: Courses
        public async Task<ActionResult> ViewCourses()
        {
            var courses = db.Courses.Include(c => c.Department).Include(c => c.Semester);
            return View(await courses.ToListAsync());
        }

        //// GET: Courses/Details/5
        //public async Task<ActionResult> Details( int? id )
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Course course = await db.Courses.FindAsync(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(course);
        //}

        // GET: Courses/Save
        public ActionResult Save()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name");
            return View();
        }

        // POST: Courses/Save
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save( [Bind(Include = "CourseId,Code,Name,Credit,Description,DepartmentId,SemesterId")] Course course )
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                await db.SaveChangesAsync();
                db.SaveChanges();
                TempData["Msg"] = "Course Successfully Saved";
                return RedirectToAction("Save");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
            return View(course);
        }

        //GET: Validation

        public JsonResult IsCodeAvailble( string code )
        {
            var courseCode = db.Courses.FirstOrDefault(x => x.Code == code);
            if (courseCode != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);

            }
        }
        public JsonResult IsNameAvailble( string name )
        {
            var courseName = db.Courses.FirstOrDefault(x => x.Name == name);

            if (courseName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);

            }
        }



        // GET: Courses/Edit/5
        //public async Task<ActionResult> Edit( int? id )
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Course course = await db.Courses.FindAsync(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
        //    ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
        //    return View(course);
        //}

        //// POST: Courses/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit( [Bind(Include = "CourseId,Code,Name,Credit,Description,DepartmentId,SemesterId,AssignTo,Grade,Status,ScheduleInfo")] Course course )
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(course).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("ViewCourses");
        //    }
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
        //    ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
        //    return View(course);
        //}

        //// GET: Courses/Delete/5
        //public async Task<ActionResult> Delete( int? id )
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Course course = await db.Courses.FindAsync(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(course);
        //}

        //// POST: Courses/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed( int id )
        //{
        //    Course course = await db.Courses.FindAsync(id);
        //    db.Courses.Remove(course);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("ViewCourses");
        //}

        protected override void Dispose( bool disposing )
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UCRMS-V-1.0/Controllers/MyControllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UCRMS_V_1._0.Models.MyContext;
using UCRMS_V_1._0.Models.MyModels;

namespace UCRMS_V_1._0.Controllers.MyControllers
{
    public class StudentsController : Controller
    {
        private UcrmsDbContext db = new UcrmsDbContext();

        // GET: Students
        public async Task<ActionResult> ViewStudents()
        {
            var students = db.Students.Include(s => s.Department);
            return View(await students.ToListAsync());
        }

        // GET: Students/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Student student = await db.Students.FindAsync(id);
        //    if (student == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(student);
        //}

        // GET: Students/Register
        public ActionResult Register()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            DateTime dateTime = DateTime.Now;
            ViewBag.Date = dateTime;
            return View();
        }

        // POST: Students/Register
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register( [Bind(Include = "StudentId,Name,Email,Date,ContactNo,Address,DepartmentId")] Student student )
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                student.RegNo = GetRegNo(student);
                await db.SaveChangesAsync();
                TempData["Msg"] = "New Student Successfully Registerd!";
                return RedirectToAction("Register");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", student.DepartmentId);
            DateTime dateTime = DateTime.Now;
            ViewBag.Date = dateTime;
            return View(student);
        }
        //GET: Students/RegNo
        public string GetRegNo( Student student )
        {
            int id = db.Students.Count(t => (t.DepartmentId == student.DepartmentId) && (t.Date.Year == student.Date.Year)) + 1;

            Department department = db.Departments.FirstOrDefault(d => d.DepartmentId == student.DepartmentId);
            string deptName = department.Name;
            string regId = deptName + "-" + student.Date.Year + "-";
            int len = 3 - id.ToString().Length;
            string addZero = "";
            for (int i = 0; i < len; i++)
            {
                addZero = "0" + addZero;
            }
            return regId + addZero + id;
        }
        //GET: Students/IsEmailAvailable
        public JsonResult IsEmailAvailable( string email )
        {
            var studentEmail = db.Students.FirstOrDefault(x => x.Email == email);

            if (studentEmail != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);

            }
        }


        //// GET: Students/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Student student = await db.Students.FindAsync(id);
        //    if (student == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", student.DepartmentId);
        //    return View(student);
        //}

        //// POST: Students/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "StudentId,Name,Email,Date,ContactNo,Address,DepartmentId,ResultDate,RegNo")] Student student)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(student).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("ViewStudents");
        //    }
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", student.DepartmentId);
        //    return View(student);
        //}

        //// GET: Students/Delete/5
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Student student = await db.Students.FindAsync(id);
        //    if (student == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(student);
        //}

        //// POST: Students/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Student student = await db.Students.FindAsync(id);
        //    db.Students.Remove(student);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("ViewStudents");
        //}

        protected override void Dispose( bool disposing )
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UCRMS-V-1.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UCRMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/MyStyles/Navbar.css" rel="stylesheet" />
    <link href="~/MyStyles/round-about.css" rel="stylesheet" />

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UCRMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span>Home</a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Department <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Department", "Save", "Departments")</li>
                            <li>@Html.ActionLink("View All Departments", "ViewDepartments", "Departments")</li>

                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Course<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Course", "Save", "Courses")</li>
                            <li>@Html.ActionLink("View Course's List", "ViewCourses", "Courses")</li>
                            <li>@Html.ActionLink("Add Teacher", "Save", "Teachers")</li>
                            <li>@Html.ActionLink("View Teacher's List", "ViewTeachers", "Teachers")</li>
                            <li>@Html.ActionLink("Course Assign To Teacher", "Assign", "AssignCourses")</li>
                            <li>@Html.ActionLink("View Assigning Courses", "Assign", "AssignCourses")</li>
                            <li>@Html.ActionLink("View Course Statics", "ViewCourseStatics", "AssignCourses")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Student<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student", "Register", "Students")</li>
                            <li>@Html.ActionLink("View Register's Student", "ViewStudents", "Students")</li>
                            <li>@Html.ActionLink("Enroll In a Course", "Enroll", "EnrollCourses")</li>
                            <li>@Html.ActionLink("View Enroll's Courses", "ViewEnrollCourses", "EnrollCourses")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Room<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate ClassRooms", "Allocate", "AllocateClassRooms")</li>
                            <li>@Html.ActionLink("View Class Schedule", "ViewSchedule", "AllocateClassRooms")</li>
                            <li>@Html.ActionLink("View All Allocations", "ViewAllocations", "AllocateClassRooms")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Result<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Student Result", "SaveResult", "SaveResults")</li>
                            <li>@Html.ActionLink("View Result", "ViewResult", "SaveResults")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Clear<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Unassign All Courses", "UnAssignCourse", "AssignCourses")</li>
                            <li id="unallocate">@Html.ActionLink("Unallocate All ClassRooms", "UnallocateClassRoom", "AllocateClassRooms")</li>
                        </ul>
                    </li>


                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>




    <div class="col-md-2" id="sideBar">
        <div class="margin-top-20">
            <a href="@Url.Action("Index", "Home")" class="btn btn-info btn-large btn-block"><span class="glyphicon glyphicon-home"></span>Home</a>
            <br />
            <a href="@Url.Action("Save", "Departments")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-floppy-disk"></span>Save Departmet</a>
            <a href="@Url.Action("ViewDepartments", "Departments")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-eye-open"></span>View All Department</a>
            <br/>
            <a href="@Url.Action("Save", "Courses")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-floppy-disk"></span>Save Course</a>
            <a href="@Url.Action("Save", "Teachers")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-user"></span>Save Teacher</a>
            <br/>
             <a href="@Url.Action("Assign", "AssignCourses")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-adjust"></span>AssignCourse</a>
            <a href="@Url.Action("ViewCourseStatics", "AssignCourses")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-eye-open"></span>View Course Statics</a>
            <br />
            <a href="@Url.Action("Register", "Students")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-user"></span>Register Sudent</a>
            <br/>
            <a href="@Url.Action("Allocate", "AllocateClassRooms")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-time"></span>Allocate Class Room</a>
            <a href="@Url.Action("ViewSchedule", "AllocateClassRooms")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-eye-open"></span>View Class Schedule</a>
            <br />
            <a href="@Url.Action("Enroll", "EnrollCourses")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-dashboard"></span>Enroll Course</a>
            <br />
            <a href="@Url.Action("SaveResult", "SaveResults")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-floppy-disk"></span>Save Student Result</a>
            <a href="@Url.Action("ViewResult", "SaveResults")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-eye-open"></span>View Result</a>
            <br />
            <a href="@Url.Action("UnAssignCourse", "AssignCourses")" class="btn btn-danger btn-large btn-block"><span class="glyphicon glyphicon-trash"></span>Unassign Courses</a>
            <a href="@Url.Action("UnallocateClassRoom", "AllocateClassRooms")" class="btn btn-danger btn-large btn-block"><span class="glyphicon glyphicon-trash"></span>Unallocate Rooms</a>

        </div>
    </div>
    <div class="col-md-10">
        <div class="container body-content">
            @RenderBody()
            <hr />
        </div>
    </div>




    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="container" align="center">
            <p style="font-size: 18px; margin-top: 8px; color: white"> Developed By: &copy; @DateTime.Now.Year - MVC-KING (Team)</p>
        </div>
    </nav>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>